### ISSUE TITLE
Login Credentials added to Starter Kit and Code Pattern

### ISSUE THREAD

**Issue by lemacomb** [IBM/Integrate-Investment-Portfolio#19]
Add login credentials to the Starter Kit and Code Pattern so the end user doesn't need to create an account and add the credentials.

Benefit:  Creating an account often deters an end user.  By embedding default credentials, the end user can exercise the pattern / starter kit immediately.  End user can be told how to create their own account and supply their credentials.

Discussed with Raheel already.  Laura and Abtin are aware of this request.

**Comment by raheelzubairy** [comment]
@lemacomb I have added default quovo credentials for the code pattern and starter-kit. Thanks
